/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista.Bancos;
// Angoly Camila Araujo Mayen 9959-24-17
import Controlador.Bancos.clsBitacoraBancaria;
import Controlador.clsUsuarioConectado;
import Modelo.Bancos.BitacoraBancariaDAO;
import java.io.File;
import java.util.Date;
import java.util.List;

public class frmBitacoraBancaria extends javax.swing.JInternalFrame {

    // ── Campos de la clase ────────────────────────────────────
    private final BitacoraBancariaDAO bitacoraDAO = new BitacoraBancariaDAO();

    // ── Constructor ────────────────────────────────────────────
public frmBitacoraBancaria() {
    initComponents();
    cargarTodos();
    // Ocultar fechas por defecto
    jLabel1.setVisible(false);
    jLabel2.setVisible(false);
    fechaInicio.setVisible(false);
    fechaFin.setVisible(false);
}

// ── Cargar toda la bitácora en la tabla ────────────────────
private void cargarTodos() {
    List<clsBitacoraBancaria> lista = bitacoraDAO.listar();
    llenarTabla(lista);
}

// ── Llenar la JTable con una lista ────────────────────────
private void llenarTabla(List<clsBitacoraBancaria> lista) {
    javax.swing.table.DefaultTableModel modelo =
        (javax.swing.table.DefaultTableModel) tablaBitacora.getModel();
    modelo.setRowCount(0); // Limpiar filas anteriores

    for (clsBitacoraBancaria b : lista) {
        modelo.addRow(new Object[]{
            b.getBBid(),
            b.getBBusuarioaccion(),
            b.getBBaccion(),
            b.getBBtabla(),
            b.getBBregistroid(),
            b.getBBvaloranterior(),
            b.getBBvalornuevo(),
            b.getBBfechaaccion(),
            b.getBBdescripcion()
        });
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fechaInicio = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        cboxTipoBusqueda = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaBitacora = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fechaFin = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel3.setText("Bitácora Bancaria ");

        cboxTipoBusqueda.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cboxTipoBusqueda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Código", "Usuario", "Accion", "Tabla", "Registro", "Valor Anterioir", "Valor nuevo", "Fechas", "Descripción" }));
        cboxTipoBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxTipoBusquedaActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton2.setText("Ayuda");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        txtBuscar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });

        btnBuscar.setBackground(new java.awt.Color(255, 227, 250));
        btnBuscar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnLimpiar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        tablaBitacora.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Usuario", "Acción", "Tabla", "Registro", "Valor Anterior", "Valor Nuevo", "Fecha", "Descripción"
            }
        ));
        jScrollPane2.setViewportView(tablaBitacora);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Fecha Inicio:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Fecha Fin:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(43, 286, Short.MAX_VALUE)
                        .addComponent(btnBuscar)
                        .addGap(47, 47, 47)
                        .addComponent(btnLimpiar)
                        .addGap(30, 30, 30))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(124, 124, 124))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(14, 14, 14))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cboxTipoBusqueda, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtBuscar))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(321, 321, 321)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel3)
                .addGap(30, 30, 30)
                .addComponent(cboxTipoBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fechaInicio, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(fechaFin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscar)
                    .addComponent(btnLimpiar)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboxTipoBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxTipoBusquedaActionPerformed
    boolean esFecha = cboxTipoBusqueda.getSelectedItem().equals("Fechas");
    
    txtBuscar.setVisible(!esFecha);
    jLabel1.setVisible(esFecha);
    jLabel2.setVisible(esFecha);
    fechaInicio.setVisible(esFecha);
    fechaFin.setVisible(esFecha);
    }//GEN-LAST:event_cboxTipoBusquedaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
   String tipo = (String) cboxTipoBusqueda.getSelectedItem();
    String texto = txtBuscar.getText().trim();
    List<clsBitacoraBancaria> lista = bitacoraDAO.listar(); // base completa
    List<clsBitacoraBancaria> resultado = new java.util.ArrayList<>();

    try {
        switch (tipo) {
            case "Código":
                if (!texto.isEmpty()) {
                    clsBitacoraBancaria b = bitacoraDAO.query(Integer.parseInt(texto));
                    if (b != null) resultado.add(b);
                } else resultado = lista;
                break;

            case "Usuario":
                for (clsBitacoraBancaria b : lista)
                    if (String.valueOf(b.getBBusuarioaccion()).contains(texto))
                        resultado.add(b);
                break;

            case "Accion":
                for (clsBitacoraBancaria b : lista)
                    if (b.getBBaccion() != null &&
                        b.getBBaccion().toLowerCase().contains(texto.toLowerCase()))
                        resultado.add(b);
                break;

            case "Tabla":
                resultado = bitacoraDAO.queryPorTabla(texto);
                break;

            case "Registro":
                for (clsBitacoraBancaria b : lista)
                    if (b.getBBregistroid() != null &&
                        String.valueOf(b.getBBregistroid()).contains(texto))
                        resultado.add(b);
                break;

            case "Valor Anterioir":
                for (clsBitacoraBancaria b : lista)
                    if (b.getBBvaloranterior() != null &&
                        b.getBBvaloranterior().toLowerCase().contains(texto.toLowerCase()))
                        resultado.add(b);
                break;

            case "Valor nuevo":
                for (clsBitacoraBancaria b : lista)
                    if (b.getBBvalornuevo() != null &&
                        b.getBBvalornuevo().toLowerCase().contains(texto.toLowerCase()))
                        resultado.add(b);
                break;

            case "Fechas":
                Date inicio = fechaInicio.getDate();
                Date fin    = fechaFin.getDate();
                if (inicio == null || fin == null) {
                    javax.swing.JOptionPane.showMessageDialog(this,
                        "Seleccione ambas fechas.", "Aviso",
                        javax.swing.JOptionPane.WARNING_MESSAGE);
                    return;
                }
                for (clsBitacoraBancaria b : lista) {
                    Date fa = b.getBBfechaaccion();
                    if (fa != null && !fa.before(inicio) && !fa.after(fin))
                        resultado.add(b);
                }
                break;

            case "Descripción":
                for (clsBitacoraBancaria b : lista)
                    if (b.getBBdescripcion() != null &&
                        b.getBBdescripcion().toLowerCase().contains(texto.toLowerCase()))
                        resultado.add(b);
                break;

            default:
                resultado = lista;
        }

        llenarTabla(resultado);

        if (resultado.isEmpty())
            javax.swing.JOptionPane.showMessageDialog(this,
                "No se encontraron registros.", "Información",
                javax.swing.JOptionPane.INFORMATION_MESSAGE);

    } catch (NumberFormatException ex) {
        javax.swing.JOptionPane.showMessageDialog(this,
            "Ingrese un número válido para buscar por Código o Registro.", "Error",
            javax.swing.JOptionPane.ERROR_MESSAGE);
    }

    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
       txtBuscar.setText("");
    fechaInicio.setDate(null);
    fechaFin.setDate(null);
    cboxTipoBusqueda.setSelectedIndex(0);
    // El cambio de índice dispara cboxTipoBusquedaActionPerformed
    // que ya oculta las fechas y muestra txtBuscar
    cargarTodos();
    }//GEN-LAST:event_btnLimpiarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JComboBox<String> cboxTipoBusqueda;
    private com.toedter.calendar.JDateChooser fechaFin;
    private com.toedter.calendar.JDateChooser fechaInicio;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablaBitacora;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
 }    
