//Karina Alejandra Arriaza Ortiz 9959-24-14190
package Vista.Bancos;

import Controlador.Bancos.clsConciliacionBancaria;
import Modelo.Bancos.ConciliacionBancariaDAO;
import java.sql.Connection;
//import net.sf.jasperreports.engine.JasperCompileManager;
//import net.sf.jasperreports.engine.JasperFillManager;
//import net.sf.jasperreports.engine.JasperPrint;
//import net.sf.jasperreports.engine.JasperReport;
//import net.sf.jasperreports.view.JasperViewer;


public class frmConciliacionBancaria extends javax.swing.JInternalFrame {

    private final ConciliacionBancariaDAO dao = new ConciliacionBancariaDAO();

    public frmConciliacionBancaria() {
        initComponents();
        setClosable(true);
        setMaximizable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("Cat. Estado Conciliación");
        cargarTabla();
        configurarSeleccionTabla();
        setDefaultCloseOperation(javax.swing.JInternalFrame.DISPOSE_ON_CLOSE);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        txtid = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnReporte = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        txtid1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("MS Gothic", 2, 12)); // NOI18N
        jLabel2.setText("ID:");

        jLabel3.setFont(new java.awt.Font("MS Gothic", 2, 12)); // NOI18N
        jLabel3.setText("Fecha:");

        jTextField1.setFont(new java.awt.Font("MS Gothic", 2, 12)); // NOI18N

        txtid.setFont(new java.awt.Font("MS Gothic", 2, 12)); // NOI18N
        txtid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidActionPerformed(evt);
            }
        });

        btnAgregar.setFont(new java.awt.Font("MS Gothic", 2, 12)); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnEliminar.setFont(new java.awt.Font("MS Gothic", 2, 12)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnActualizar.setFont(new java.awt.Font("MS Gothic", 2, 12)); // NOI18N
        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnBuscar.setFont(new java.awt.Font("MS Gothic", 2, 12)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnReporte.setFont(new java.awt.Font("MS Gothic", 2, 12)); // NOI18N
        btnReporte.setText("Reportes");
        btnReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("MS Gothic", 2, 14)); // NOI18N
        jLabel1.setText("Conciliación Bancaria:");

        jLabel4.setFont(new java.awt.Font("MS Gothic", 2, 12)); // NOI18N
        jLabel4.setText("Cuenta Bancaria:");

        jTextField2.setFont(new java.awt.Font("MS Gothic", 2, 12)); // NOI18N

        jLabel5.setFont(new java.awt.Font("MS Gothic", 2, 12)); // NOI18N
        jLabel5.setText("Saldo Banco:");

        jTextField3.setFont(new java.awt.Font("MS Gothic", 2, 12)); // NOI18N

        jTextField4.setFont(new java.awt.Font("MS Gothic", 2, 12)); // NOI18N

        txtid1.setFont(new java.awt.Font("MS Gothic", 2, 12)); // NOI18N

        jLabel6.setFont(new java.awt.Font("MS Gothic", 2, 12)); // NOI18N
        jLabel6.setText("Saldo Sistema:");

        jLabel7.setFont(new java.awt.Font("MS Gothic", 2, 12)); // NOI18N
        jLabel7.setText("Diferencia:");

        jComboBox1.setFont(new java.awt.Font("MS Gothic", 2, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Conciliada", "Pendiente", "Con Diferencia" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("MS Gothic", 2, 12)); // NOI18N
        jLabel8.setText("Estado:");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Fecha", "Cuenta", "Saldo Sistema", "Saldo Banco", "Diferencia", "Estado"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtid1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnAgregar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnBuscar))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnActualizar)
                                        .addGap(28, 28, 28)
                                        .addComponent(btnEliminar)))
                                .addGap(28, 28, 28)
                                .addComponent(btnReporte)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(90, 90, 90)
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap())))))
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 744, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnAgregar)
                                .addComponent(btnBuscar))
                            .addGap(30, 30, 30)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnActualizar)
                                .addComponent(btnEliminar)))
                        .addComponent(btnReporte))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addGap(11, 11, 11)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtid1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(206, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        if (!camposCompletos()) return;

        try {
            clsConciliacionBancaria cates = getConciliacionBancariaDeFormulario();
            dao.insert(cates);
            javax.swing.JOptionPane.showMessageDialog(this,
                "Estado de conciliación registrado correctamente.",
                "Éxito", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            cargarTabla();
            limpiarCampos();
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Error al agregar: " + e.getMessage(),
                "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if (txtid.getText().trim().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Seleccione un estado de conciliación bancaria de la tabla o ingrese un ID.",
                "Atención", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        int confirm = javax.swing.JOptionPane.showConfirmDialog(this,
            "¿Está seguro de que desea eliminar este de conciliación bancaria?",
            "Confirmar eliminación", javax.swing.JOptionPane.YES_NO_OPTION);
        if (confirm != javax.swing.JOptionPane.YES_OPTION) return;

        try {
            int id = Integer.parseInt(txtid.getText().trim());
            dao.delete(id);
            javax.swing.JOptionPane.showMessageDialog(this,
                "Estado de conciliación eliminado correctamente.",
                "Éxito", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            cargarTabla();
            limpiarCampos();
        } catch (NumberFormatException ex) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "El ID debe ser un número válido.",
                "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Error al eliminar: " + e.getMessage(),
                "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        if (txtid.getText().trim().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Seleccione un estado de conciliación de la tabla para actualizar.",
                "Atención", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (!camposCompletos()) return;

        try {
            clsConciliacionBancaria cates = getConciliacionBancariaDeFormulario();
            cates.setCatesid(Integer.parseInt(txtid.getText().trim()));
            dao.update(cates);
            javax.swing.JOptionPane.showMessageDialog(this,
                "Estado de conciliación actualizado correctamente.",
                "Éxito", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            cargarTabla();
            limpiarCampos();
        } catch (NumberFormatException ex) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "El ID debe ser un número válido.",
                "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Error al actualizar: " + e.getMessage(),
                "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        if (txtid.getText().trim().isEmpty()) {
    javax.swing.JOptionPane.showMessageDialog(this,
        "Ingrese un ID para buscar.",
        "Atención", javax.swing.JOptionPane.WARNING_MESSAGE);
    return;
}
try {
    int id = Integer.parseInt(txtid.getText().trim());
    clsConciliacionBancaria cb = dao.query(id);
    if (cb != null) {
        //jDateChooser1.setDate(cb.getConbfecha());
        jTextField1.setText(String.valueOf(cb.getConbsaldosistema()));
        jTextField2.setText(String.valueOf(cb.getConbsaldobanco()));
        jTextField3.setText(String.valueOf(cb.getConbdiferencia()));
        jTextField4.setText(String.valueOf(cb.getCBANid()));
        //jTextField5.setText(String.valueOf(cb.getCatesid()));
    } else {
        javax.swing.JOptionPane.showMessageDialog(this,
            "No se encontró una conciliación bancaria con ID: " + id,
            "Sin resultados", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        limpiarCampos();
    }
} catch (NumberFormatException ex) {
    javax.swing.JOptionPane.showMessageDialog(this,
        "El ID debe ser un número válido.",
        "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
} catch (Exception e) {
    javax.swing.JOptionPane.showMessageDialog(this,
        "Error al buscar: " + e.getMessage(),
        "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
}
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteActionPerformed
        Connection conn = null;
        try {
            conn = Modelo.Conexion.getConnection();

            // Ruta corregida — faltaba el separador entre getAbsolutePath() y src
            String ruta = new java.io.File("").getAbsolutePath()
            + "\\src\\main\\java\\Reportes\\Bancos\\ConciliacionBancaria.jrxml";

            System.out.println("Buscando reporte en: " + ruta); // Para verificar en consola

            java.io.File archivo = new java.io.File(ruta);
            if (!archivo.exists()) {
                javax.swing.JOptionPane.showMessageDialog(this,
                    "No se encontró el archivo del reporte en:\n" + ruta,
                    "Archivo no encontrado", javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }

            java.util.Map<String, Object> parametros = new java.util.HashMap<>();

            //net.sf.jasperreports.engine.JasperReport reporte =
            //   net.sf.jasperreports.engine.JasperCompileManager.compileReport(ruta);

            //net.sf.jasperreports.engine.JasperPrint print =
            //    net.sf.jasperreports.engine.JasperFillManager.fillReport(reporte, parametros, conn);

            //net.sf.jasperreports.engine.JasperExportManager.exportReportToPdfFile(print,"reporte.pdf");
            //net.sf.jasperreports.swing.JRViewer viewer = new net.sf.jasperreports.swing.JRViewer(print);

            javax.swing.JFrame frame = new javax.swing.JFrame("Reporte de Estado Conciliacion");
            frame.setSize(800, 600);
            frame.setLocationRelativeTo(null);
            frame.setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
            //frame.add(viewer);
            frame.setVisible(true);

        } catch (Exception e) {
            e.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(this,
                "Error al generar el reporte:\n" + e.getMessage(),
                "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        } finally {
            if (conn != null) {
                try { conn.close(); } catch (Exception ex) { ex.printStackTrace(); }
            }
        }
    }//GEN-LAST:event_btnReporteActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void txtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidActionPerformed

// ── Llena la tabla con todos los estados de conciliación ────────────────────
private void cargarTabla() {
    javax.swing.table.DefaultTableModel modelo = new javax.swing.table.DefaultTableModel(
        new String[]{"ID", "Fecha", "Saldo Sistema", "Saldo Banco", "Diferencia", "ID Cuenta", "ID Estado"}, 0
    ) {
        @Override
        public boolean isCellEditable(int r, int c) { return false; }
    };
    for (clsConciliacionBancaria cb : dao.listar()) {
        modelo.addRow(new Object[]{
            cb.getConbid(),
            cb.getConbfecha(),
            cb.getConbsaldosistema(),
            cb.getConbsaldobanco(),
            cb.getConbdiferencia(),
            cb.getCBANid(),
            cb.getCatesid()
        });
    }
    jTable1.setModel(modelo);
}

// ── Limpia todos los campos ──────────────────────────────────
private void limpiarCampos() {
    txtid.setText("");
    jTextField1.setText("");
    jTable1.clearSelection();
}

// ── Valida que los campos no estén vacíos ───────────────────
private boolean camposCompletos() {
    if (jTextField1.getText().trim().isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this,
            "Complete todos los campos: Nombre Estado.",
            "Campos incompletos", javax.swing.JOptionPane.WARNING_MESSAGE);
        return false;
    }
    return true;
}
private void configurarSeleccionTabla() {
    jTable1.getSelectionModel().addListSelectionListener(e -> {
        if (!e.getValueIsAdjusting() && jTable1.getSelectedRow() != -1) {
            int fila = jTable1.getSelectedRow();
            txtid.setText(jTable1.getValueAt(fila, 0).toString());      // ID
            jTextField1.setText(jTable1.getValueAt(fila, 1).toString()); // Nombre Estado
        }
    });
}

// ── Crea el objeto clsConciliacionBancaria desde los campos del formulario ─
private clsConciliacionBancaria getConciliacionBancariaDeFormulario() {
    clsConciliacionBancaria cb = new clsConciliacionBancaria(
        0,                                                         // ID lo genera MySQL con AUTO_INCREMENT
        //new java.util.Date(jDateChooser1.getDate().getTime()),     // Fecha
        Double.parseDouble(jTextField1.getText().trim()),           // Saldo Sistema
        Double.parseDouble(jTextField2.getText().trim()),           // Saldo Banco
        Double.parseDouble(jTextField3.getText().trim()),           // Diferencia
        Integer.parseInt(jTextField4.getText().trim())             // ID Cuenta Bancaria
        //Integer.parseInt(jTextField5.getText().trim())              // ID Estado
    );
    return cb;
}
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmConciliacionBancaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmConciliacionBancaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmConciliacionBancaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmConciliacionBancaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmConciliacionBancaria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnReporte;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtid1;
    // End of variables declaration//GEN-END:variables
}
